FROM unblibraries/jdk:oracle7
MAINTAINER Jacob Sanford <jsanford_at_unb.ca>

ENV CRAWL_DOMAINS localhost.com
ENV OPERATOR_CONTACT_URL http://change.me.com
ENV JAVA_OPTS -Xmx512m

ENV HERITRIX_ADMIN_USER heritrix
ENV HERITRIX_ADMIN_PASS heritrix
ENV HERITRIX_ADMIN_PORT 8443
ENV HERITRIX_BIND_HOST 0.0.0.0

ENV HERITRIX_VERSION 3.2.0
ENV FOREGROUND true
ENV HERITRIX_DATA_DIR /mnt/heritrix_data
ENV HERITRIX_JOBS_DIR ${HERITRIX_DATA_DIR}/jobs

ENV ROBOTS_POLICY_NAME obey
ENV DELAY_FACTOR 5.0
ENV MIN_DELAY_MS 3000
ENV RESPECT_CRAWL_DELAY_UP_TO_SECONDS 300
ENV MAX_DELAY_MS 30000
ENV MAX_PER_HOST_BANDWIDTH 0
ENV MAX_TOE_THREADS 25
ENV PAUSE_AT_START false
ENV SNOOZE_LONG_MS 5000
ENV RETRY_DELAY_SECONDS 30
ENV MAX_CRAWL_RETRIES 10
ENV DISPOSITION_DELAY_FACTOR 0
ENV DISPOSITION_MIN_DELAY_MS 500
ENV DISPOSITION_MAX_DELAY_MS 1000
ENV REGEX_IGNORE_VALUES <value>bibliography.*</value>

ENV HERITRIX_INSTALL_TMP_DIR /tmp
ENV HERITRIX_INSTALL_ROOT /opt/heritrix
ENV HERITRIX_HOME ${HERITRIX_INSTALL_ROOT}
ENV HERITRIX_BIN_PATH ${HERITRIX_INSTALL_ROOT}/bin
ENV HERITRIX_ARCHIVE_FILENAME heritrix-${HERITRIX_VERSION}-dist.tar.gz
ENV HERITRIX_DOWNLOAD_URL http://builds.archive.org/maven2/org/archive/heritrix/heritrix/${HERITRIX_VERSION}/${HERITRIX_ARCHIVE_FILENAME}
ENV HERITRIX_USER heritrix
ENV HERITRIX_USER_ID 918

RUN wget -v -O ${HERITRIX_INSTALL_TMP_DIR}/${HERITRIX_ARCHIVE_FILENAME} ${HERITRIX_DOWNLOAD_URL}
WORKDIR ${HERITRIX_INSTALL_TMP_DIR}
RUN tar xvzpf ${HERITRIX_ARCHIVE_FILENAME} && \
  mv ${HERITRIX_INSTALL_TMP_DIR}/heritrix-${HERITRIX_VERSION} ${HERITRIX_INSTALL_ROOT}

# Add running user
RUN useradd -u ${HERITRIX_USER_ID} -U -s /bin/false ${HERITRIX_USER} && \
  usermod -G users ${HERITRIX_USER} && \
  chown -R ${HERITRIX_USER}:users ${HERITRIX_INSTALL_ROOT}

RUN mkdir -p ${HERITRIX_DATA_DIR}
ADD conf/heritrix/jobs ${HERITRIX_DATA_DIR}/jobs
RUN chown -R ${HERITRIX_USER}:users ${HERITRIX_DATA_DIR}

CMD ["/sbin/my_init"]

# Copy phusion/baseimage inits.
ADD init/ /etc/my_init.d/
ADD services/ /etc/service/
RUN chmod -v +x /etc/service/*/run
RUN chmod -v +x /etc/my_init.d/*.sh

# Clean up.
RUN apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE ${HERITRIX_ADMIN_PORT}
